spring:
  datasource:
    #MySQL配置
    url: jdbc:mysql://server-addr:3306/gulimall_sms?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: gulimall_sms
    password: wB5fJHE36sK2T7z2
    driverClassName: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: ${spring.cloud.nacos.server-addr}
      server-addr: server-addr:8848
  application:
    name: gulimall-coupon
#
#mybatis-plus:
#  mapper-locations: classpath*/:/mapper/**/*.xml
#  global-config:
#    db-config:
#      id-type: auto

server:
  port: 7000
